// Tangled from gomoku.loom by the Loom CLI.
// Do not edit this file directly — change the loom and re-tangle.

import { Array, Effect, Match, Option, Order, Schema as S, pipe } from 'effect'
import { type Command, define } from 'foldkit/command'
import { html } from 'foldkit/html'
import { m } from 'foldkit/message'
import { defineView } from 'foldkit/submodel'

export const SIZE = 15
const WIN = 5

export type Player = 'black' | 'white'
export type Cell = Player | 'broken' | null
export type Board = ReadonlyArray<Cell>

const inBounds = (row: number, col: number): boolean =>
  row >= 0 && row < SIZE && col >= 0 && col < SIZE

export const emptyBoard: Board = Array.makeBy(
  SIZE * SIZE,
  () => null,
)

const other = (player: Player): Player =>
  player === 'black' ? 'white' : 'black'

export const move = (
  board: Board,
  cell: number,
  player: Player,
): Board =>
  board[cell] === null
    ? board.map((existing, index) =>
        index === cell ? player : existing,
      )
    : board

export const detonate = (
  board: Board,
  cell: number,
): Board =>
  board.map((existing, index) =>
    index === cell ? 'broken' : existing,
  )

export const full = (board: Board): boolean =>
  board.every((cell) => cell !== null)

const DIRECTIONS: ReadonlyArray<
  readonly [number, number]
> = [
  [0, 1],
  [1, 0],
  [1, 1],
  [1, -1],
]

const cellAt = (
  board: Board,
  row: number,
  col: number,
): Cell =>
  inBounds(row, col) ? board[row * SIZE + col] : null

const lineWinner = (
  board: Board,
  row: number,
  col: number,
  dRow: number,
  dCol: number,
): Player | null => {
  const start = cellAt(board, row, col)
  if (start === null || start === 'broken') {
    return null
  }
  const complete = Array.range(1, WIN - 1).every(
    (step) =>
      cellAt(
        board,
        row + dRow * step,
        col + dCol * step,
      ) === start,
  )
  return complete ? start : null
}

const eachLine = <A>(
  read: (
    row: number,
    col: number,
    dRow: number,
    dCol: number,
  ) => A,
): ReadonlyArray<A> =>
  pipe(
    Array.range(0, SIZE - 1),
    Array.flatMap((row) =>
      Array.flatMap(
        Array.range(0, SIZE - 1),
        (col) =>
          Array.map(
            DIRECTIONS,
            ([dRow, dCol]) =>
              read(row, col, dRow, dCol),
          ),
      ),
    ),
  )

export const winner = (
  board: Board,
): Player | null =>
  pipe(
    eachLine((row, col, dRow, dCol) =>
      lineWinner(board, row, col, dRow, dCol),
    ),
    Array.findFirst(
      (found): found is Player => found !== null,
    ),
    Option.getOrNull,
  )

const lineCells = (
  row: number,
  col: number,
  dRow: number,
  dCol: number,
): ReadonlyArray<number> =>
  Array.map(
    Array.range(0, WIN - 1),
    (step) =>
      (row + dRow * step) * SIZE +
      (col + dCol * step),
  )

export const winningLine = (
  board: Board,
): ReadonlyArray<number> =>
  pipe(
    eachLine((row, col, dRow, dCol) =>
      lineWinner(board, row, col, dRow, dCol) === null
        ? Option.none<ReadonlyArray<number>>()
        : Option.some(lineCells(row, col, dRow, dCol)),
    ),
    Array.getSomes,
    Array.head,
    Option.getOrElse(() => []),
  )

const rayLength = (
  board: Board,
  row: number,
  col: number,
  dRow: number,
  dCol: number,
  player: Player,
): number =>
  cellAt(board, row, col) === player
    ? 1 +
      rayLength(
        board,
        row + dRow,
        col + dCol,
        dRow,
        dCol,
        player,
      )
    : 0

const wonAt = (board: Board, cell: number): boolean => {
  const player = board[cell]
  if (
    player === null ||
    player === undefined ||
    player === 'broken'
  ) {
    return false
  }
  const row = Math.floor(cell / SIZE)
  const col = cell % SIZE
  return DIRECTIONS.some(
    ([dRow, dCol]) =>
      1 +
        rayLength(
          board,
          row + dRow,
          col + dCol,
          dRow,
          dCol,
          player,
        ) +
        rayLength(
          board,
          row - dRow,
          col - dCol,
          -dRow,
          -dCol,
          player,
        ) >=
      WIN,
  )
}

const rayCells = (
  row: number,
  col: number,
  dRow: number,
  dCol: number,
): ReadonlyArray<number> =>
  inBounds(row, col)
    ? [
        row * SIZE + col,
        ...rayCells(row + dRow, col + dCol, dRow, dCol),
      ]
    : []

const range = Array.range(0, SIZE - 1)
const rest = Array.range(1, SIZE - 1)

const LINE_STARTS: ReadonlyArray<
  readonly [number, number, number, number]
> = [
  ...Array.map(range, (r) => [r, 0, 0, 1] as const),
  ...Array.map(range, (c) => [0, c, 1, 0] as const),
  ...Array.map(range, (c) => [0, c, 1, 1] as const),
  ...Array.map(rest, (r) => [r, 0, 1, 1] as const),
  ...Array.map(range, (c) => [0, c, 1, -1] as const),
  ...Array.map(rest, (r) => [r, SIZE - 1, 1, -1] as const),
]

const LINE_CELLS: ReadonlyArray<
  ReadonlyArray<number>
> = pipe(
  LINE_STARTS,
  Array.map(([row, col, dRow, dCol]) =>
    rayCells(row, col, dRow, dCol),
  ),
  Array.filter((cells) => cells.length >= WIN),
)

const glyph = (cell: Cell): string =>
  Match.value(cell).pipe(
    Match.when('white', () => 'w'),
    Match.when('black', () => 'b'),
    Match.when('broken', () => 'x'),
    Match.orElse(() => '.'),
  )

const lineText = (
  board: Board,
  cells: ReadonlyArray<number>,
): string =>
  cells.map((cell) => glyph(board[cell])).join('')

const brokenThree = (me: string): RegExp =>
  new RegExp(
    `\\.${me}{2}\\.${me}\\.|\\.${me}\\.${me}{2}\\.`,
    'g',
  )

const patternsFor = (
  me: string,
): ReadonlyArray<readonly [RegExp, number]> => [
  [new RegExp(`\\.${me}{4}\\.`, 'g'), 100_000],
  [new RegExp(`${me}{4}`, 'g'), 10_000],
  [new RegExp(`\\.${me}{3}\\.`, 'g'), 5_000],
  [brokenThree(me), 4_000],
  [new RegExp(`${me}{3}`, 'g'), 500],
  [new RegExp(`\\.${me}{2}\\.`, 'g'), 100],
]

const WHITE_PATTERNS = patternsFor('w')
const BLACK_PATTERNS = patternsFor('b')

const DEFENCE = 1.1

const countIn = (
  lines: ReadonlyArray<string>,
  pattern: RegExp,
): number =>
  Array.reduce(
    lines,
    0,
    (total, line) =>
      total + (line.match(pattern)?.length ?? 0),
  )

const patternScore = (
  lines: ReadonlyArray<string>,
  patterns: ReadonlyArray<readonly [RegExp, number]>,
): number =>
  Array.reduce(
    patterns,
    0,
    (total, [pattern, weight]) =>
      total + countIn(lines, pattern) * weight,
  )

const evaluate = (board: Board): number => {
  const lines = Array.map(LINE_CELLS, (cells) =>
    lineText(board, cells),
  )
  return (
    patternScore(lines, WHITE_PATTERNS) -
    DEFENCE * patternScore(lines, BLACK_PATTERNS)
  )
}

const CENTER = Math.floor((SIZE * SIZE) / 2)
const REACH = 2
const WIDTH = 14

const NEIGHBOURHOOD: ReadonlyArray<
  readonly [number, number]
> = pipe(
  Array.range(-REACH, REACH),
  Array.flatMap((dRow) =>
    Array.map(
      Array.range(-REACH, REACH),
      (dCol) => [dRow, dCol] as const,
    ),
  ),
  Array.filter(
    ([dRow, dCol]) => dRow !== 0 || dCol !== 0,
  ),
)

const neighbours = (
  board: Board,
  cell: number,
): number => {
  const row = Math.floor(cell / SIZE)
  const col = cell % SIZE
  return pipe(
    NEIGHBOURHOOD,
    Array.filter(
      ([dRow, dCol]) =>
        cellAt(board, row + dRow, col + dCol) !==
        null,
    ),
    Array.length,
  )
}

const runThrough = (
  board: Board,
  cell: number,
  player: Player,
): number => {
  const row = Math.floor(cell / SIZE)
  const col = cell % SIZE
  return Math.max(
    ...Array.map(DIRECTIONS, ([dRow, dCol]) =>
      rayLength(
        board,
        row + dRow,
        col + dCol,
        dRow,
        dCol,
        player,
      ) +
      rayLength(
        board,
        row - dRow,
        col - dCol,
        -dRow,
        -dCol,
        player,
      ),
    ),
  )
}

const urgency = (board: Board, cell: number): number =>
  Math.max(
    runThrough(board, cell, 'white'),
    runThrough(board, cell, 'black'),
  )

const byUrgency = (board: Board): Order.Order<number> =>
  Order.mapInput(
    Order.Number,
    (cell: number) => -urgency(board, cell),
  )

const candidates = (
  board: Board,
): ReadonlyArray<number> =>
  board.every((cell) => cell === null)
    ? [CENTER]
    : pipe(
        Array.range(0, SIZE * SIZE - 1),
        Array.filter(
          (cell) =>
            board[cell] === null &&
            neighbours(board, cell) > 0,
        ),
        Array.sort(byUrgency(board)),
        Array.take(WIDTH),
      )

const WIN_SCORE = 1_000_000
const DEPTH = 2

const step = (
  board: Board,
  toMove: Player,
  depth: number,
  alpha: number,
  beta: number,
  moves: ReadonlyArray<number>,
  best: number,
): number => {
  if (moves.length === 0) {
    return best
  }
  const [cell, ...rest] = moves
  const score = minimax(
    move(board, cell, toMove),
    other(toMove),
    depth - 1,
    alpha,
    beta,
    cell,
  )
  const white = toMove === 'white'
  const nextBest = white
    ? Math.max(best, score)
    : Math.min(best, score)
  const nextAlpha = white ? Math.max(alpha, nextBest) : alpha
  const nextBeta = white ? beta : Math.min(beta, nextBest)
  if (nextAlpha >= nextBeta) {
    return nextBest
  }
  return step(
    board,
    toMove,
    depth,
    nextAlpha,
    nextBeta,
    rest,
    nextBest,
  )
}

const minimax = (
  board: Board,
  toMove: Player,
  depth: number,
  alpha: number,
  beta: number,
  lastCell: number,
): number => {
  if (wonAt(board, lastCell)) {
    return toMove === 'white' ? -WIN_SCORE : WIN_SCORE
  }
  if (depth === 0 || full(board)) {
    return evaluate(board)
  }
  const start = toMove === 'white' ? -Infinity : Infinity
  return step(
    board,
    toMove,
    depth,
    alpha,
    beta,
    candidates(board),
    start,
  )
}

export const bestMove = (board: Board): number =>
  pipe(
    candidates(board),
    Array.reduce(
      { cell: CENTER, value: -Infinity },
      (best, cell) => {
        const value = minimax(
          move(board, cell, 'white'),
          'black',
          DEPTH,
          -Infinity,
          Infinity,
          cell,
        )
        return value > best.value
          ? { cell, value }
          : best
      },
    ),
    (best) => best.cell,
  )

const CellSchema = S.NullOr(
  S.Literals(['black', 'white', 'broken']),
)

export const Model = S.Struct({
  board: S.Array(CellSchema),
  bombs: S.Array(S.Number),
  phase: S.Literals(['idle', 'thinking']),
  lastMove: S.NullOr(S.Number),
})
export type Model = typeof Model.Type

export const init: Model = {
  board: emptyBoard,
  bombs: [],
  phase: 'idle',
  lastMove: null,
}

const BOMB_BLOCK_ROWS = 3
const BOMB_BLOCK_COLS = 5
const BLOCK_HEIGHT = SIZE / BOMB_BLOCK_ROWS
const BLOCK_WIDTH = SIZE / BOMB_BLOCK_COLS

const randomBombs = (): ReadonlyArray<number> =>
  Array.makeBy(
    BOMB_BLOCK_ROWS * BOMB_BLOCK_COLS,
    (block) => {
      const band = Math.floor(block / BOMB_BLOCK_COLS)
      const file = block % BOMB_BLOCK_COLS
      const row =
        band * BLOCK_HEIGHT +
        Math.floor(Math.random() * BLOCK_HEIGHT)
      const col =
        file * BLOCK_WIDTH +
        Math.floor(Math.random() * BLOCK_WIDTH)
      return row * SIZE + col
    },
  )

export const newGame = (): Model => ({
  board: emptyBoard,
  bombs: randomBombs(),
  phase: 'idle',
  lastMove: null,
})

export const Played = m('Played', { cell: S.Number })
export const ComputerMoved = m('ComputerMoved', { cell: S.Number })
export const BombsPlaced = m('BombsPlaced', { bombs: S.Array(S.Number) })
export const Reset = m('Reset')

export const Message = S.Union([Played, ComputerMoved, BombsPlaced, Reset])
export type Message = typeof Message.Type

const h = html<Message>()

export const ThinkThenMove = define(
  'ThinkThenMove',
  { board: S.Array(CellSchema) },
  ComputerMoved,
)(({ board }) =>
  Effect.sleep('220 millis').pipe(
    Effect.andThen(
      Effect.sync(() =>
        ComputerMoved({ cell: bestMove(board) }),
      ),
    ),
  ),
)

export const ArmBombs = define('ArmBombs', BombsPlaced)(
  Effect.sync(() => BombsPlaced({ bombs: randomBombs() })),
)

export type Return = readonly [
  Model,
  ReadonlyArray<Command<Message>>,
]

const over = (board: Board): boolean =>
  winner(board) !== null || full(board)

type Placed = {
  board: Board
  bombs: ReadonlyArray<number>
  lastMove: number | null
}

const place = (
  model: Model,
  cell: number,
  player: Player,
): Placed =>
  model.bombs.includes(cell)
    ? {
        board: detonate(model.board, cell),
        bombs: model.bombs.filter(
          (bomb) => bomb !== cell,
        ),
        lastMove: model.lastMove,
      }
    : {
        board: move(model.board, cell, player),
        bombs: model.bombs,
        lastMove: player === 'white' ? cell : model.lastMove,
      }

const playHuman = (
  model: Model,
  cell: number,
): Return => {
  if (
    model.phase !== 'idle' ||
    over(model.board) ||
    model.board[cell] !== null
  ) {
    return [model, []]
  }
  const { board, bombs, lastMove } = place(
    model,
    cell,
    'black',
  )
  return over(board)
    ? [{ board, bombs, lastMove, phase: 'idle' }, []]
    : [
        { board, bombs, lastMove, phase: 'thinking' },
        [ThinkThenMove({ board })],
      ]
}

const playComputer = (
  model: Model,
  cell: number,
): Return => {
  const { board, bombs, lastMove } = place(
    model,
    cell,
    'white',
  )
  return [
    { board, bombs, lastMove, phase: 'idle' },
    [],
  ]
}

export const update = (model: Model, message: Message): Return =>
  Match.value(message).pipe(
    Match.withReturnType<Return>(),
    Match.tagsExhaustive({
      Played: ({ cell }) => playHuman(model, cell),
      ComputerMoved: ({ cell }) => playComputer(model, cell),
      BombsPlaced: ({ bombs }) => [{ ...model, bombs }, []],
      Reset: () => [init, [ArmBombs()]],
    }),
  )

const cellClass = (
  cell: Cell,
  won: boolean,
  last: boolean,
  mine: boolean,
): string => {
  const base = Match.value(cell).pipe(
    Match.when('black', () => 'gomoku-cell black'),
    Match.when('white', () => 'gomoku-cell white'),
    Match.when('broken', () => 'gomoku-cell broken'),
    Match.orElse(() => 'gomoku-cell'),
  )
  const withWin = won ? `${base} win` : base
  const withLast = last ? `${withWin} last` : withWin
  return mine ? `${withLast} mine` : withLast
}

const winCells = (
  model: Model,
): ReadonlyArray<number> => {
  if (
    model.phase !== 'idle' ||
    winner(model.board) === null
  ) {
    return []
  }
  return winningLine(model.board)
}

const revealedBombs = (
  model: Model,
): ReadonlyArray<number> =>
  over(model.board) ? model.bombs : []

const cellSquare =
  (
    won: ReadonlySet<number>,
    lastMove: number | null,
    mines: ReadonlySet<number>,
  ) =>
  (cell: Cell, index: number) =>
    h.div(
      [
        h.Class(
          cellClass(
            cell,
            won.has(index),
            index === lastMove,
            mines.has(index),
          ),
        ),
        h.OnClick(Played({ cell: index })),
      ],
      [],
    )

export const view = defineView<Model, Message>(
  (model) =>
    h.div(
      [
        h.Class(
          model.phase === 'thinking'
            ? 'gomoku thinking'
            : 'gomoku',
        ),
      ],
      [
        h.div(
          [h.Class('gomoku-grid')],
          model.board.map(
            cellSquare(
              new Set(winCells(model)),
              model.lastMove,
              new Set(revealedBombs(model)),
            ),
          ),
        ),
      ],
    ),
)
